config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :roles do
  	collection do
  		patch 'update_multiple'
  	end
  end
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :role
	has_many :user_meta_infos, dependent: :destroy
	has_many :images, dependent: :destroy

	accepts_nested_attributes_for :images, :user_meta_infos

end

app/models/user_meta_info.rb
class UserMetaInfo < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  def index
    @roles = Role.all
  end

  # GET /roles/1
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to @role, notice: 'Role was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /roles/1
  def update
    if @role.update(role_params)
      redirect_to @role, notice: 'Role was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /roles/1
  def destroy
    @role.destroy
    redirect_to roles_url, notice: 'Role was successfully destroyed.'
  end

  #PATCH/PUT /roles/update_multiple/ids=[]
  def update_multiple
    @roles = Role.where(id: params[:role_ids])
    @roles.update_all(status: false)
    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def role_params
      params.require(:role).permit(:name, :description, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @images = @user.images.build
    @user_meta_infos = @user.user_meta_infos
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(first_name: user_params[:first_name], last_name: user_params[:last_name],
      email: user_params[:email], role:Role.find(user_params[:role]))

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.where(id: params[:id]).first
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :role, 
        images_attributes: [:id, :user_id, :avatar],
        user_meta_infos_attributes: [:id, :user_id, :meta_key, :meta_value]
        )
    end
end

app/helpers/application_helper.rb
# app/helpers/application_helper.rb
module ApplicationHelper

    # This method creates a link with `data-id` `data-fields` attributes. These attributes are used to create new instances of the nested fields through Javascript.
    def link_to_add_fields(name, f, association)

        # Takes an object (@person) and creates a new instance of its associated model (:addresses)
        # To better understand, run the following in your terminal:
        # rails c --sandbox
        # @person = Person.new
        # new_object = @person.send(:addresses).klass.new
        new_object = f.object.send(association).klass.new

        # Saves the unique ID of the object into a variable. 
        # This is needed to ensure the key of the associated array is unique. This is makes parsing the content in the `data-fields` attribute easier through Javascript.
        # We could use another method to achive this.
        id = new_object.object_id

        # https://api.rubyonrails.org/ fields_for(record_name, record_object = nil, fields_options = {}, &block) 
        # record_name = :addresses
        # record_object = new_object
        # fields_options = { child_index: id }
            # child_index` is used to ensure the key of the associated array is unique, and that it matched the value in the `data-id` attribute.
            # `person[addresses_attributes][child_index_value][_destroy]`
        fields = f.fields_for(association, new_object, child_index: id) do |builder|
            
            # `association.to_s.singularize + "_fields"` ends up evaluating to `address_fields`
            # The render function will then look for `views/people/_address_fields.html.erb`
            # The render function also needs to be passed the value of 'builder', because `views/people/_address_fields.html.erb` needs this to render the form tags.
            render(association.to_s.singularize + "_fields", f: builder)
        end

        # This renders a simple link, but passes information into `data` attributes.
            # This info can be named anything we want, but in this case we chose `data-id:` and `data-fields:`.
        # The `id:` is from `new_object.object_id`.
        # The `fields:` are rendered from the `fields` blocks.
            # We use `gsub("\n", "")` to remove anywhite space from the rendered partial.
        # The `id:` value needs to match the value used in `child_index: id`.
        link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
        
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lotvue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light">
      <a class="navbar-brand" href="#">Lotvue</a>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Roles
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Add Role", new_role_path, class: "dropdown-item" %>
            <%= link_to "Hide Roles", roles_path, class: "dropdown-item" %>
          </div>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Users
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Add User", new_user_path, class: "dropdown-item" %>
            <%= link_to "Show Users", users_path, class: "dropdown-item" %>
          </div>
        </li>
      </ul>

      <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">About Us</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <div class="form-group">
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  
    <%= form.label :status %>
    <%= form.check_box :status, class: 'form-control' %>
  
    <%= form.submit 'Submit', class: 'btn btn-success' %>
  </div>  
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles</h1>

<%= form_tag update_multiple_roles_path, method: :patch do %>

<table class="table table-bordered table-hover">
  <thead class="thead-light">
    <tr>
      <th>Select</th>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= check_box_tag "role_ids[]", role.id, false, class: 'selectable' %></td>
        <td><%= role.name %></td>
        <td><%= role.description %></td>
        <td><%= role.status %></td>
        <td><%= link_to 'Show', role %>
        <%= link_to 'Edit', edit_role_path(role) %>
        <%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= submit_tag "Update selected", :class => 'btn btn-primary btn-xs' %>
<% end %>
<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @role.status %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |form| %>
  <div class="form-group">
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= form.label :first_name %>
  <%= form.text_field :first_name, class: 'form-control' %>

  <%= form.label :last_name %>
  <%= form.text_field :last_name, class: 'form-control' %>
  
  <%= form.label :email %>
  <%= form.text_field :email, class: 'form-control' %>

  <%= form.label :role %>
  <%= form.select(:role, Role.all.collect {|u| [u.name, u.id]}, {}, {class: "form-control"})%>

  <fieldset>
    <legend>Images:</legend>
    <%= form.fields_for :images do |images_field| %>
      <%= render "image_fields", f: images_field %> 

    <% end %>
    <%= link_to_add_fields "Add Images", form, :images %>
  </fieldset>

  <fieldset>
    <legend>Images:</legend>
    <%= form.fields_for :user_meta_infos do |meta_info| %>
      <%= render "user_meta_info_fields", f: meta_info %> 

    <% end %>
    <%= link_to_add_fields "Add Meta Info", form, :user_meta_infos %>
  </fieldset>

  <%= form.submit 'Submit', class: 'btn btn-success'  %>
  
<% end %>

app/views/users/_image_fields.html.erb
<%# app/views/people/_image_fields.html.erb %>
<div class="nested-fields">
    <%= f.hidden_field :_destroy %>
    <div>
	  <%= f.label :avatar %>
	  <%= f.file_field :avatar,:multiple => true,name: "images_attributes[image][]" %>
	</div>
    <div>
        <%= link_to "Remove", '#', class: "remove_fields" %>
    </div>
</div>

app/views/users/_user_meta_info_fields.html.erb
<div class="nested-fields">
    <%= f.hidden_field :_destroy %>
    <div>
        <%= f.label :meta_key %>
        <%= f.text_field :meta_key, class: 'form-control' %>
    </div>
    <div>
        <%= f.label :meta_value %>
        <%= f.text_field :meta_value, class: 'form-control' %>
    </div>
    <div>
        <%= link_to "Remove", '#', class: "remove_fields" %>
    </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>